version: "3"

services:
  postgres:
    image: "postgres:latest"
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
